### ISSUE TITLE
Add ability to configure how result is projects

### ISSUE THREAD

**Issue by Rohland** [Rohland/barky#26]
It would be neat for each evaluator to override how the result is projected, i..e. for a web check

```yaml
web:
  some-api:
    url: https://www.codeo.co.za/api/test
    status: 200
    result: "status: {{ status }}, data: {{ data }}"
```
